import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import { Toaster } from "sonner";
import "./globals.css";

const roboto = Roboto({ subsets: ["latin"], weight: "700" });

export const metadata: Metadata = {
  title: "Next Azure Cloud",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr">
      <body className={roboto.className}>
        <Toaster position="bottom-right" richColors />
        <main>{children}</main>
      </body>
    </html>
  );
}
